### ISSUE TITLE
Я конечно извеняюсь.. Но тут у вас баг 

### ISSUE THREAD

**Issue by dwsVad** [MailRuChamps/miniaicups#1]
Описание: Репа пустая.
Шаги воспроизведения:
1.Открыть любо браузер
2. Перейти по урлу: https://github.com/MailRuChamps/miniaicups

Ожидания: Много файликов.
Фактический результат:   Почти пустой ридми, лицензия и ... пустота :(

**Comment by sat2707** [comment]
Доброго дня. Репа будет постепенно наполняться вплоть до 26 марта, мы
писали об этом. Репорт не закрываю, пусть висит до 26 :)

20 мар. 2018 г. 16:11 пользователь "Vad" <notifications@github.com> написал:
