### ISSUE TITLE
Визулизатор на сайте: разбросало по углам

### ISSUE THREAD

**Issue by babazhanov** [MailRuChamps/miniaicups#100]
Где то на 1600 тике жёлтого при попадании на вирус раскидало по углам. После этого он так и не собрался...
[Игра](http://aicups.ru/session/87239/)
![default](https://user-images.githubusercontent.com/8986256/38176527-5e406538-35f9-11e8-8a98-3d40fcc4dcb9.png)

**Comment by BorisKolganov** [comment]
Такое происходит, когда у стратегии выходит лимит по времени.
