### ISSUE TITLE
Параметры конфигурации игры в плеере

### ISSUE THREAD

**Issue by alex3d** [MailRuChamps/miniaicups#104]
Нужно показывать в плеере на сайте параметры конфигурации игры (MAX_FRAGS_CNT etc)

**Comment by alex3d** [comment]
Если места нет можно показывать в тултипе/поповере.
// тикет не критичный конечно

**Comment by 99peso** [comment]
не критичный, но каждый раз еще и лог качать чтобы посмотреть 2-3 параметра, тоже неохота
