### ISSUE TITLE
Дублируются объекты, передаваемые стратегии

### ISSUE THREAD

**Issue by areytsman** [MailRuChamps/miniaicups#107]
При количестве своих фрагментов > 1 локалраннер дублирует некоторые из объектов.
Выглядит это так:
![image](https://user-images.githubusercontent.com/12498008/38193347-4f7cc178-367a-11e8-8709-3d3e17e65e20.png)
При этом на stdin стратегии приходит такое:
`{"Mine": [{"Id": "1.2", "M": 170.76638034401137, "R": 26.13552221357066, "SX": 0.004701245038712854, "SY": -0.02001223785264206, "TTF": 39, "X": 614.6817076020201, "Y": 297.3779499128626}, {"Id": "1.1", "M": 173.68757236401137, "R": 26.3581161970283, "SX": -0.027610943436156048, "SY": 0.015228340654364035, "TTF": 39, "X": 622.6747633866569, "Y": 343.5779538642128}], "Objects": [{"T": "F", "X": 651, "Y": 366}, {"T": "F", "X": 621, "Y": 403}, {"T": "F", "X": 595, "Y": 428}, {"T": "F", "X": 631, "Y": 411}, {"T": "F", "X": 651, "Y": 366}, {"T": "F", "X": 564, "Y": 415}, {"Id": "20", "M": 40, "T": "V", "X": 273, "Y": 120}, {"Id": "21", "M": 40, "T": "V", "X": 387, "Y": 120}, {"Id": "22", "M": 40, "T": "V", "X": 387, "Y": 540}, {"Id": "23", "M": 40, "T": "V", "X": 273, "Y": 540}, {"Id": "264", "M": 40, "T": "V", "X": 227, "Y": 115}, {"Id": "265", "M": 40, "T": "V", "X": 433, "Y": 115}, {"Id": "266", "M": 40, "T": "V", "X": 433, "Y": 545}, {"Id": "267", "M": 40, "T": "V", "X": 227, "Y": 545}]}`
Видно, что одна еда дублируется.

**Comment by FDoKE** [comment]
Скажу больше, дублируется все что видит каждый фрагмент. Скорее всего это баг + дополнительная лишняя информация для обработки.

**Comment by VexfxjC** [comment]
пофиксил, отправил на проверку

**Comment by sat2707** [comment]
вылечено
