### ISSUE TITLE
[BUG] в safari не работает потиковая прокрутка визуализатора с клавиатуры

### ISSUE THREAD

**Issue by Karloid** [MailRuChamps/miniaicups#110]
1) кликаем на ползунок времени
2) нажимаем вперед\назад
3) никакой реакции

в хроме на этой же машине работает.

![image](https://user-images.githubusercontent.com/2398460/38193803-9d378838-367c-11e8-8419-fc12f6cc5ed8.png)

**Comment by sat2707** [comment]
Дали кнопок. Лечить сафари к сожалению нет сейчас времени :(
