### ISSUE TITLE
Сколько доступно места на диске для сохранения данных нейросети?

### ISSUE THREAD

**Issue by eSkry** [MailRuChamps/miniaicups#122]

**Comment by kswaldemar** [comment]
Обещали минимум 20mb для исходников, точнее могут сказать только организаторы.
Сохранять какие-то данные между играми на сервере нельзя.

**Comment by sat2707** [comment]
Сохранять данные __между__ играми действительно нельзя. На вход принимается до 20мб архивированных данных
