### ISSUE TITLE
Текст на спрайте при отладочном просмотре

### ISSUE THREAD

**Issue by sat2707** [MailRuChamps/miniaicups#133]
Текст мелкий, шрифт блеклый.

**Comment by tongohiti** [comment]
![sprite_text_hardly_visible](https://user-images.githubusercontent.com/15714232/38376893-50853b56-3902-11e8-8081-9ed4b4e26f14.png)

Для поломки органов зрения.

**Comment by tongohiti** [comment]
Заметил ещё одну проблему со спрайтом. Если сначала вывести в спрайт текст, а через некоторое время убрать его, то в визуализаторе старый текст ещё болтается привязанным к спрайту некоторое время, хотя должен по идее пропасть сразу же. При этом если при висящем протухшем тексте приостановить проигрывание и сделать "тик назад" или "тик вперёд" с помощью полосы прокрутки, то текст на спрайте пропадёт.

**Comment by tongohiti** [comment]
Ещё проблема со спрайтом: при потиковом просмотре (в браузере стрелочками влево/вправо) текст на спрайте не отображается, этого очень не хватает, т.к. там висит ключевая информация о текущем поведении стратегии.
