### ISSUE TITLE
добавить TICK_MS в jsonConfig

### ISSUE THREAD

**Issue by adler3d** [MailRuChamps/miniaicups#135]
Так как CPU Time дешёвое и постоянно дешевеет, то было бы круто, если бы стратегия получала константу GAME_TIMELIMIT через jsonConfig.

типа:
GAME_TIMELIMIT_PER_FRAME=20; // ms

никогда не поздно увеличить TL :)

**Comment by sat2707** [comment]
А это не дубль https://github.com/MailRuChamps/miniaicups/issues/109 ? :)

**Comment by adler3d** [comment]
#146 - готово :)
