### ISSUE TITLE
Влияние вязкости среды

### ISSUE THREAD

**Issue by dolphin278** [MailRuChamps/miniaicups#14]
В правилах говорится, о том, что вязкость (VISCOSITY) замедляет объекты, есть информация, что он приходит как входной параметр, но в формуле скорости он не учитывается (да и ни в одной другой формуле в правилах не фигурирует).

**Comment by kswaldemar** [comment]
Думаю стоит подождать исходники локалраннера, там будут все расчеты.

**Comment by dolphin278** [comment]
Да, себе выковыряем, но в правила хорошо бы все равно добавить.

**Comment by sat2707** [comment]
Добавили
