### ISSUE TITLE
Возможно, что-то с логгированием

### ISSUE THREAD

**Issue by sat2707** [MailRuChamps/miniaicups#140]
http://aicups.ru/session/97608/ лог у красного начинается со 2 тика

**Comment by sat2707** [comment]
Возможно это все же что-то с работой со стратегией
http://aicups.ru/session/95921/ аналогичный случай

**Comment by WatsOne** [comment]
еще в копилку
http://aicups.ru/session/103449/

**Comment by 99peso** [comment]
попарсил несколько игр

**Comment by 99peso** [comment]
попарсил несколько своих игр (только для четвертого игрока)
url, количество ошибок, тик первой ошибки

http://aicups.ru/session/108291/ 2859 T4465
+P3.4 X210.2099073283017 Y573.4389200032983 A-1.264887062639244
+P2.2 X230.7835897281535 Y446.8377913849444 A1.149949674025878
+P1.2 X399.756314511611 Y571.6874813303452 A-0.701481034358608
+P2.5 X207.166044038041 Y509.6774664633768 A1.362967994613146
+P3.6 X241.1374954436807 Y551.3397518286287 A-1.582907441265737
+P4.2 X227.6187036570161 Y555.0490507112271 A1.782866508424212
+P3.3 X234.900129961507 Y607.078968712299 A-1.255683171059772
+P3.5 X148.1615777069866 Y710.5785346068031 A-1.074077839573818
+P2.3 X253.4959649594895 Y542.3789467605637 A1.886400913344361
+P2.4 X233.9647991904511 Y524.1219315335359 A1.520780825397213
+P1.1 X483.8060542607446 Y546.9945310804978 A-0.2905918273153545
+P4.1 X230.9864501104455 Y539.4074944003795 A-1.358726145165581
KP4.2
KP2.3
KP4.1
AP2.6 X230.7835897281535 Y446.8377913849444 R21.83993016593105 M119.2456374131863 C9 F0
+P2.2 R21.83993016593105 M119.2456374131863 I2.7
KV21
+P3.6 X241.1374954436807 Y551.3397518286287 R38.00141987431402 M361.026978115977
P2 C207
P3 C395
+P2.7 F109.1996508296553
+P3.6 F190.0070993715701
+P2.6 F109.1996508296553
C1.2 X449.748736811059 Y572.5579482358988
C1.1 X532.153085846743 Y559.7446109556386
C2.7 X225.8537985062336 Y397.0814133163161
C2.5 X211.1166963223278 Y459.8337873603185
C2.4 X230.252262078812 Y474.259951346276
C2.6 X225.8537985062336 Y397.0814133163161
C3.4 X215.2233656812035 Y523.6909026021624
C3.6 X205.0027745442357 Y516.7813672379217
C3.3 X222.9168184544537 Y558.5362015340166
C3.5 X165.2013155513764 Y663.5716485772599


http://aicups.ru/session/107601/ 2776 T3807
+P1 X581.9671694749131 Y174.7436282332156 A-2.015779904310461
+P3 X941.7524130462787 Y909.4368164572732 A1.60148075733722
+P4 X941.9949191254748 Y874.9828672055368 A1.572343631538921
KF667
KP3
+P4 X931.0138937890141 Y874.9828672055368 R58.98610621098589 M869.8401814834269
P4 C348
+P4 F235.9444248439436
C1 X630.0561384766613 Y161.0523514356009


http://aicups.ru/session/107521/ 3657 T2766
+P4.2 X532.6248464130972 Y576.4828472148362 A-2.175035022002393
+P2.1 X525.0528527782143 Y684.3219201448607 A0.5681450618302184
+P2.2 X500.7522679792576 Y687.391448753643 A0.3562728546535273
+P2.3 X471.5451210186953 Y672.2821900247856 A0.5708766318965911
+P2.4 X495.1244055074234 Y649.5112950913904 A0.01069793087208211
+P2.5 X526.4282945458165 Y651.1448972410626 A0.3859468276312635
+P2.6 X550.8387871006156 Y673.4908938005185 A0.3471001631890821
+P4.1 X515.1834055723798 Y548.0676848419363 A-2.128506328098304
C2.1 X562.3217834387211 Y717.6539888988749
C2.2 X546.4262607288074 Y707.7356466074309
C2.3 X516.7913516141876 Y693.560785300309
C2.4 X530.0144558369053 Y685.3258785457072
C2.5 X548.2815719716687 Y696.1163800468223
C2.6 X557.4806875591099 Y723.0477819019667


http://aicups.ru/session/107230/ 3704 T41
+P1 X60.14080379618481 Y60.14080379618481 A-2.356194490192345
+P2 X783.4629926462895 Y197.2982077063847 A1.406298762152248e-05
+P3 X548.7669940190082 Y632.3050113764414 A1.937947517141665
+P4 X185.4070579464634 Y482.7744313767098 A-1.789386280499
C3 X575.3169749330301 Y674.6736142972962
C3 X576.2135523269222 Y674.0983892855106


http://aicups.ru/session/107192/ 1435 T15
+P1 X140.7620679548221 Y433.1837443300148 A-1.884980935282629
+P2 X777.840825387939 Y423.5141286858419 A-2.767880195899375
+P3 X843.7895370893798 Y535.3671913527735 A-0.8869693463658548
+P4 X139.2380043572937 Y462.2822556956931 A-1.678683606397827
C3 X812.2016401917457 Y574.1254778162439
C2 X729.9765505346236 Y409.0569092863076


http://aicups.ru/session/107521/ 3657 T2766
+P4.2 X532.6248464130972 Y576.4828472148362 A-2.175035022002393
+P2.1 X525.0528527782143 Y684.3219201448607 A0.5681450618302184
+P2.2 X500.7522679792576 Y687.391448753643 A0.3562728546535273
+P2.3 X471.5451210186953 Y672.2821900247856 A0.5708766318965911
+P2.4 X495.1244055074234 Y649.5112950913904 A0.01069793087208211
+P2.5 X526.4282945458165 Y651.1448972410626 A0.3859468276312635
+P2.6 X550.8387871006156 Y673.4908938005185 A0.3471001631890821
+P4.1 X515.1834055723798 Y548.0676848419363 A-2.128506328098304
C2.1 X562.3217834387211 Y717.6539888988749
C2.2 X546.4262607288074 Y707.7356466074309
C2.3 X516.7913516141876 Y693.560785300309
C2.4 X530.0144558369053 Y685.3258785457072
C2.5 X548.2815719716687 Y696.1163800468223
C2.6 X557.4806875591099 Y723.0477819019667

**Comment by BorisKolganov** [comment]
Пофиксили, повторяться больше не должно
