### ISSUE TITLE
Не работает скомпилированный local_runner для linux Ubuntu 14.04.

### ISSUE THREAD

**Issue by stepuncius** [MailRuChamps/miniaicups#149]
При нажатии старт вылетает.
Если запустить из консоли пишет:

`r$ ./local_runner   

./local_runner: symbol lookup error: ./local_runner: undefined symbol: _ZN7QString13toUtf8_helperERKS_
`

**Comment by kswaldemar** [comment]
Предположу, что у вас слишком старая версия Qt. В Ubuntu 16.04, которой пользуются организаторы, Qt версии `5.5.1`
