### ISSUE TITLE
В каких пределах могут меняться физические константы?

### ISSUE THREAD

**Issue by Xeenych** [MailRuChamps/miniaicups#150]
Какие максимальные и минимальные могут быть значения параметров игровой физики?
    double INERTION_FACTOR;     // 10.0
    double VISCOSITY;           // 0.25
    double SPEED_FACTOR;        // 25.0

    double FOOD_MASS;           // 1.0
    double VIRUS_RADIUS;        // 22.0
    double VIRUS_SPLIT_MASS;    // 80.0
    int MAX_FRAGS_CNT;          // 10
    int TICKS_TIL_FUSION;       // 250 ticks

**Comment by tyamgin** [comment]
В [правилах](https://github.com/MailRuChamps/miniaicups/blob/master/agario/RULES.md) же написано.

* ключи GAME_WIDTH и GAME_HEIGHT - размеры мира (int);
* GAME_TICKS - длительность игры в тиках (int);
* FOOD_MASS - масса еды (float) (меняется от 1.0 до 4.0);
* MAX_FRAGS_CNT - максимальное количество фрагментов у одного игрока (int) (от 4 до 16);
* TICKS_TIL_FUSION - кол-во тиков после деления или взрыва, когда можно слить фрагменты (int) (от 150 до 500);
* VIRUS_RADIUS - радиус вируса (float) (от 15.0 до 40.0);
* VIRUS_SPLIT_MASS - критическая масса, по достижению которой вирус поделится (float) (от 50.0 до 100.0)
* VISCOSITY - вязкость среды, от которой зависит скорость замедления вирусов, выбросов и фрагментов после деления (float) (от 0.05 - наименьшая вязкость, до 0.5)
* INERTION_FACTOR - параметр регулировки инерции (насколько быстро изменяется вектор скорости при смене направления) (float) (от 1.0 - наибольшая инерция, до 20.0)
* SPEED_FACTOR - параметр регулировки максимальной скорости (float) (от 25.0 до 100.0 - космические скорости)
