### ISSUE TITLE
еда/фрагменты выбрасываються не туда куда показывает курсор/команда

### ISSUE THREAD

**Issue by adler3d** [MailRuChamps/miniaicups#152]
Актуально когда большая инерция(нет вязкости/трения, низкая манёвренность).

В оригинале на этом была основана куча трюков:
1) внезапный join/split на догоняющего. //сейчас пока развернёшься он уже убежит.
2) просто внезапный split на только что попавшего в область видимости.
3) быстрый двойной сплит в двух разных направления. // актуально когда есть один очень большой фрагмент, т.к можно первым сплитом значительно расширить область видимости, а вторым сожрать только что обнаруженную мелочь.
4) и самое главное: можно быстро было перекачать массу из всех своих фрагментов в один и тем самым на*ъ оппонента. // наводим курсор на свой фрагмент, жмём много раз eject, и он становиться самым большим фрагмент.

**Comment by adler3d** [comment]
ещё кстати можно было двигаться со скоростью которая меньше максимальной, достаточно было держать курсор не далеко от центра экран/фрагмента.

типа:
```
vec2d get_force(Fragment fragment,Cmd cmd)
{
  const double max_spd_dist=10; // 
  static const double force_scale=random_double();
  vec2d force_dir=fragment.pos-cmd.pos;
  if(force_dir.length()>max_speed_dist)return force_dir.normalize()*max_speed_dist*force_scale;
  return force_dir*force_scale;
}
```

**Comment by alex3d** [comment]
Это не баг, а фича. В правилах `Выброс улетит вдоль текущего вектора скорости`
