### ISSUE TITLE
Кнопка "скачать дамп" иногда выдаёт битый JSON-лог

### ISSUE THREAD

**Issue by tongohiti** [MailRuChamps/miniaicups#160]
Формат JSON-лога определён так:
`````
<config JSON>

T1
<state JSON>
<strategy answer JSON>

T2
<state JSON>
<strategy answer JSON>

. . . .
T<tick number>
<state JSON>
<strategy answer JSON>
`````

Иногда в выдаваемом JSON для некотрых тиков отсутствует строчка `<strategy answer JSON>`, зто затрудняет машинный парсинг лога для локального реплея.

Пример: http://aicups.ru/game_dump/268125
Здесь испорчены T455, T461, T466, T479 и т.д., много битых тиков.

А также в некоторых тиках наоборот, задваивается строчка `<strategy answer JSON>`
Например, T756, T949 итд

**Comment by tongohiti** [comment]
Стратегия в этой игре тоже вела себя весьма неадекватно, может и ей приходили какие-то левые данные? Пытаюсь это выяснить по логу, а он битый. :(

**Comment by tyamgin** [comment]
+1
http://aicups.ru/session_debug/110169/
http://aicups.ru/game_dump/270702

**Comment by 99peso** [comment]
http://aicups.ru/session/117817/  T5491 и далее
http://aicups.ru/session/116283/  T15 и далее

**Comment by adler3d** [comment]
ещё две:
http://aicups.ru/session/125989/
http://aicups.ru/session/125990/

похоже это как-то связано с тем, что один из игроков упал/шлёт_некорректный json.

**Comment by adler3d** [comment]
ещё: http://aicups.ru/session/125990/

**Comment by adler3d** [comment]
http://aicups.ru/session/126320/

**Comment by adler3d** [comment]
нашёл баг:
https://github.com/MailRuChamps/miniaicups/blob/03262be39194e27de0550c9b321988866ab84ba7/agario/local_runner/tcp_server.h#L163

этой функции наплевать кто прислал ответ, ей самое главное чтобы их было столько же сколько и игроков.

**Comment by BorisKolganov** [comment]
Мы поправили серверный код, данная проблема должна уйти
