### ISSUE TITLE
Блокировка стратегий.

### ISSUE THREAD

**Issue by prospero78** [MailRuChamps/miniaicups#168]
Как попадаю в игру со стратегией 9110 -- так игра падает. Захожу на страницу стратегии и вижу сплошные падения.
Вы бы там придумали механизм блокировки таких глюков? Сколько раз ещё должна стратегия упасть, чтобы вы приняли меры?

**Comment by tongohiti** [comment]
__Заголовок:__ Отстранять стратегии, вызывающие падение системы, от участия в играх
__Описание:__ При игре со стратегией 9110 падает вся тестирующая система (ошибка "Сессия сломана"), при этом результаты не засчитываются для всех четырёх участников, хотя трое не виноваты. Одни и те же участники нередко играют вместе, т.к. находятся рядом в турнирной таблице.

**Comment by tongohiti** [comment]
Возможное решение. Завести счётчик падений для каждой версии стратегии. При достижении счётчиком определенного порога (2-3 игры должно быть достаточно) данная версия стратегии отстраняется от дальнейших игр. У автора должна исчезнуть опция выбора данной версии для дальнейших игр (рейтинговых или нерейтинговых).

**Comment by BorisKolganov** [comment]
Мы починили ситуации, когда одна из стратегий падает. Теперь игры с решением 9110 и подобнымми перестанут падать.
