### ISSUE TITLE
длинная строка в дебаге ломает всю сессию игры 

### ISSUE THREAD

**Issue by ivan-kudziev** [MailRuChamps/miniaicups#176]
если я правильно понял :
Tick[31] Incorrect response (unterminated string)
app.bundle.js?v=1.3.8:45550 Tick[31] Can't parse json: {"X":581.9563,"Y":909.902,"Split":false,"Debug":"                                  |||1 -->>>                                   |||2 -->>>                                   |||3 -->>>                                   |||4 --  ....

упали все стратегии
надо бы обрезать строку команды, о это не точно =( вот посмотрел другие игры ломаюсь только я....
вообщем будет время гляньте =) http://aicups.ru/session/137422/

**Comment by BorisKolganov** [comment]
Длинна строка ломает игру только тому, кто ее отправляет
