### ISSUE TITLE
Недоопределены правила

### ISSUE THREAD

**Issue by yngvix** [MailRuChamps/miniaicups#18]
Не указано, в каких пределах может меняться размер игрового поля, а это важнейший параметр.
Не сказано, что происходит при пересечении границы поля.
Непонятно, можно ли проскочить еду/другой объект за один тик, если двигаться очень быстро, или коллизии буду расчитаны в непрерывной модели.

**Comment by kswaldemar** [comment]
Размер игрового поля всегда был постоянный, думаю в этот раз также.
Все остальное станет известно как только дадут исходники локал раннера, осталось немного потерпеть.

**Comment by yngvix** [comment]
В любом случае хотелось бы, чтобы основные вещи были зафиксированы в правилах, а не только в коде игры.
