### ISSUE TITLE
Выбор рейтинговых игр

### ISSUE THREAD

**Issue by dbf256** [MailRuChamps/miniaicups#187]
Сейчас любая отправленная стратегия играет ряд игр с низом таблицы (очевидно, обыгрывая), а потом еще долго поднимается, почему бы не
1) Ставить первые игры в середину таблицы
или
2) Ставить первые игры с теми местами, где она была до публикации

**Comment by Oreshnik** [comment]
При текущей ситуации получается, что брошенные стратегии снизу таблицы играют постоянно, а стратегия же, добравшаяся, скажем, до 20 места, меньше чем через сутки перестает играть. При этом ждать своего места, чтобы оценить изменения приходится очень долго.
Логичнее было бы начинать с середины и далее двигаться двоичным поиском.

**Comment by Oreshnik** [comment]
Вот свежий сегодняшний пример. Я отправила новую версию примерно в. 13.30. Последняя моя игра - 23.48. Человек же последний раз пославший единственную версию 28 марта и находящийся снизу таблицы играет каждую волну.

**Comment by core2duo** [comment]
Поддерживаю. Если посмотреть на то, как это делает codingame, то видно, что там используется следующая стратегия:
1. Первая игра против одного из топ-10.
2а. Если свежая стратегия побеждает, то дальше она играет в основном с топ-20 - топ-30 стратегиями. Тут, очевидно, можно пытаться залить стратегию так, чтобы она победила кого-нибудь из топов, чтобы быть вверху таблицы, но в общем случае это проигрышный вариант.
2б. Если свежая стратегия проигрывает, то берется случайный игрок из низа лидерборда, дальше бинпоиск.

**Comment by DragoonXen** [comment]
не совсем первая игра из топ 10. там просто сразу кидается 10 игр по всей таблице, а дальше уже прикидывается, что делать. Получается такая пристрелка. Победил всех - начинаешь места так с 20)
