### ISSUE TITLE
Отсутствует запуск locarRunner из командной строки, без диалога

### ISSUE THREAD

**Issue by romasffm** [MailRuChamps/miniaicups#19]
А как без этого?

**Comment by m1x0n** [comment]
@romasffm Попробуйте временно собрать из исходников. При наличии установленного Qt:

```
qmake local_runner.pro
make
```

**Comment by romasffm** [comment]
Я не это имел ввиду. Не отсутствие исполняемых файлов.
А то, что нельзя запустить locarRunner с параметрами, без диалога.
