### ISSUE TITLE
Количество жизней

### ISSUE THREAD

**Issue by Baalaandaa** [MailRuChamps/miniaicups#195]
В локалраннере у игроков по 9 жизней, хотя должно быть по 5 :D

**Comment by BorisKolganov** [comment]
Всегда хотел так сказать.  Не баг, а фича. Кол-во жизней зависит от кол-ва игр, в ЛР дефолтно создается 18 игр и поэтому у игроков 9 жизней.

**Comment by SannikovDmitry** [comment]
ага, сделано для удобства
