### ISSUE TITLE
Ошибка при запуске localrunner.py

### ISSUE THREAD

**Issue by prospero78** [MailRuChamps/miniaicups#196]
Вот такой печальный лог:

> d:\coding\github.com\pyMadCars\Runners>localrunner.py > txt.log
> Traceback (most recent call last):
>   File "D:\coding\github.com\pyMadCars\Runners\localrunner.py", line 12, in <module>
>     window = pyglet.window.Window(1200, 800, vsync=False)
>   File "D:\coding\WinPython371_b4\python-3.7.0rc1.amd64\lib\site-packages\pyglet\window\win32\__init__.py", line 134, in __init__
>     super(Win32Window, self).__init__(*args, **kwargs)
>   File "D:\coding\WinPython371_b4\python-3.7.0rc1.amd64\lib\site-packages\pyglet\window\__init__.py", line 571, in __init__
>     self._create()
>   File "D:\coding\WinPython371_b4\python-3.7.0rc1.amd64\lib\site-packages\pyglet\window\win32\__init__.py", line 266, in _create
>     self.context.attach(self.canvas)
>   File "D:\coding\WinPython371_b4\python-3.7.0rc1.amd64\lib\site-packages\pyglet\gl\win32.py", line 267, in attach
>     super(Win32ARBContext, self).attach(canvas)
>   File "D:\coding\WinPython371_b4\python-3.7.0rc1.amd64\lib\site-packages\pyglet\gl\win32.py", line 212, in attach
>     raise gl.ContextException('Unable to share contexts')
> pyglet.gl.ContextException: Unable to share contexts
>

**Comment by urands** [comment]
возможно нужен python 3.6

**Comment by gitalph** [comment]
гугль говорит - это проблемка с видеодрайвером

**Comment by prospero78** [comment]
https://github.com/psychopy/psychopy/issues/1579 -- вот описание проблемы на win7 (у мя win8.1[64)
поставил анаконду с питон3.6 -- всё точно также.

**Comment by prospero78** [comment]
На текущий момент -- ничего не изменилось. Мдя. Похоже в этом сезоне -- я заявляюсь номинально))

**Comment by urands** [comment]
Как вариант, можно поставить на виртуалку (virtualbox) ubuntu

**Comment by prospero78** [comment]
Вариант, да. Но не универсально. Не мой путь.

**Comment by Pycb** [comment]
Мне, при такой же ошибке, помогло обновление драйверов видеокарты.
