### ISSUE TITLE
Добавьте плиз поддержку FreePascal (внутри созданный dockerfile и простейшая стратегия)

### ISSUE THREAD

**Issue by tumaso** [MailRuChamps/miniaicups#197]
Я, к сожалению, в создании pull requests не силен, поэтому прошу добавить поддержку FreePascal 3:

**докер (/madcars/dockers/fpc3/Dockerfile):**

FROM ubuntu:16.04
MAINTAINER Igor Kuznetsov <garry_smith@mail.ru>

RUN apt-get install fpc

ENV COMPILED_FILE_PATH=/opt/client/main
ENV SOLUTION_CODE_PATH=/opt/client/solution
ENV SOLUTION_CODE_ENTRYPOINT=main.pp
ENV COMPILATION_COMMAND='fpc -Cs67107839 -Mobjfpc -XS $SOLUTION_CODE_PATH/$SOLUTION_CODE_ENTRYPOINT -o$COMPILED_FILE_PATH 2>&1 > /dev/null'
ENV RUN_COMMAND='$COMPILED_FILE_PATH'

**простейшая стратегия (/madcars/examples/fpc3/main.pp):**

program main;

const
  COMMANDS: array[0..2] of string = ('left', 'right', 'stop');

var
  Z: string;
  Cmd: string;

begin
  while True do
  begin
    ReadLn(Z);
    Cmd := COMMANDS[Random(2)];
    WriteLn('{"command": "' + Cmd + '", "debug": "' + Cmd + '"}');
  end;
end.

**Comment by prospero78** [comment]
Люто бешенно плюсую))

**Comment by DarkNoys** [comment]
Ну чего, ну помогите человеку )

**Comment by tumaso** [comment]
DarkNoys, спасиб. Я реально пытаюсь понять, как самому делать пул реквесты. пока в процессе понимания)))

**Comment by tumaso** [comment]
Разместил pull request
