### ISSUE TITLE
localrunner broken pipe

### ISSUE THREAD

**Issue by ArtemMazyrin** [MailRuChamps/miniaicups#212]
При запуске localrunner стала вылезать ошибка:

C:\myenv\Runners>localrunner.py -f "python -u new1.py"
Loading chipmunk for Windows (32bit) [C:\Program Files (x86)\Python36-32\lib\site-packages\pymunk\chipmunk.dll]
  File "new1.py", line 11
    print(json.dumps({"command": cmd, 'debug': cmd}))
                                                    ^
TabError: inconsistent use of tabs and spaces in indentation
write exception 11887 [Errno 32] Broken pipe

Подскажите, пожалуйста, как исправить.

**Comment by UnickSoft** [comment]
Вы бы приложили файл new1.py, т.к. ошибка кажется в нём. Суть в неправильно использование табов и пробелов.

**Comment by prospero78** [comment]
> TabError: inconsistent use of tabs and spaces in indentation
Буквальный перевод:
Ошибка табуляции: несовместимое использование табов и пробелов в отступах.

**Comment by ArtemMazyrin** [comment]
@UnickSoft, @prospero78 спасибо Вам за ответы. Файл  new1.py - это переименованный пример из раздела examples. 
Сегодня всё успешно запускается, но при закрытии localrunner в терминале выдается ошибка:

Traceback (most recent call last):
  File "new1.py", line 5, in <module>
    z = input()
EOFError: EOF when reading a line

[new1.zip](https://github.com/MailRuChamps/miniaicups/files/2348218/new1.zip)

PS(я совсем в этом деле новичок, поэтому приходится постигать методом "научного тыка")

**Comment by UnickSoft** [comment]
`EOFError: EOF when reading a line`

Думаю это не страшно, значит. что просто нет входных данных.

**Comment by prospero78** [comment]
Запуск питона происходит с перенаправлением каналов чтения и записи (pipe, параметр -u).
Поэтому посреди кода такой манёвр не работает. Как и не работает диагностическая печать (в лучшем случае ввод в файл). Это неудобно после предыдущих вариантов чемпионата. Я немного плеваться начал. Хотя, справедливости ради JSON -- удобный формат обмена.
