### ISSUE TITLE
на сайте вместо последнего кадра показывается новый кадр в новом матче

### ISSUE THREAD

**Issue by adler3d** [MailRuChamps/miniaicups#217]
и ты такой:
"а? что? где? куда??? стой!!! что произошло??? кто победил-то? сколько у кого жизней отняли?"

и давай елозить мышкой, отматывать, искать где матч закончился, всматриваться где кто кому какую кнопку нажал.

сделайте что ли удобные горячие кнопки:
keyboard.left - всегда ставить просмотр на паузу и отматывать к предыдущему кадру.
keyboard.right- тоже самое только в следующему
keyboard.space - продолжить/остановить просмотр.

и ещё checkbox нужен типа - останавливать в конце каждого матча.

и ещё горячие кнопки:
ctrl+keyboard.left - предыдущий_матч/начало_матча
ctrl+keyboard.right - следующий_матч/конец_матча

**Comment by SannikovDmitry** [comment]
Зафиксим

**Comment by BorisKolganov** [comment]
Добавили rest тики и отображение в визуализаторе
