### ISSUE TITLE
double kill

### ISSUE THREAD

**Issue by adler3d** [MailRuChamps/miniaicups#221]
судя по этому коду:

            co = space.add_wildcard_collision_handler(c.get_button_collision_type())
            co.begin = partial(self.lose_callback, player)

...

    def lose_callback(self, player, arbiter, space, _):
        if not self.is_rest:
            self.dead_players.add(player)
        return False

...

    def end_match(self):
        for p in self.dead_players:
            p.die()
        return self.match_log
... 

    def die(self):
        self.lives -= 1

получается, что если два объекта(колесо+корпус) столкнуться с одной и той же кнопкой за один кадр, то игрок умрёт дважды.

**Comment by BorisKolganov** [comment]
`self.dead_players` - set(), так что думаю, нет

**Comment by adler3d** [comment]
а, да, точно, просмотрел.
