### ISSUE TITLE
localrunner (win) не работает console.readline()

### ISSUE THREAD

**Issue by Xeenych** [MailRuChamps/miniaicups#23]
Пишу на C#.
Похоже на то, что locarunner (win) не отдает в консоль данные. На вызове Console.ReadLine() бот блокируется, а localrunner сообщает о таймауте.

**Comment by devlev** [comment]
Аналогичная проблема! Только как мне кажется проблема не в readline, а в writeline. Возможно завершающий символ строки не обрабатывается. Программа из примера прогоняет ровно один цикл и во втором запуске while зависает на чтении строки из readline.

**Comment by Xeenych** [comment]
Причем, тот же код на сервере работает.

**Comment by devlev** [comment]
QByteArray cmdBytes = "";
        while (! cmdBytes.endsWith('\n')) {
            bool success = solution->waitForReadyRead(RESP_TIMEOUT * 1000);
            if (! success) {
                cmdBytes.append(solution->readAllStandardOutput());
                cmdBytes.append(solution->readAllStandardError());
                cmdBytes.append(solution->readAll());
                qDebug() << cmdBytes;
                emit error("Can't wait for process answer (5 sec. expired)");
                return Direct(0, 0);
            }
            cmdBytes.append(solution->readLine());
        }
Где то тут ошибка. У меня постоянно вылетает ошибка "Can't wait for process answer (5 sec. expired"

**Comment by Xeenych** [comment]
Возможно, cmdBytes.append(solution->readLine()); добавляет в  cmdBytes строку без '\n' в конце

**Comment by Xeenych** [comment]
Если после отправки команды сделать sleep(100), то localrunner работает, но очень медленно
Console.WriteLine(res);
Thread.Sleep(100);

Здесь что-то связано с буферезированным вводом-выводом

**Comment by Xeenych** [comment]
Есть что-нибудь новое?

**Comment by Xeenych** [comment]
Блин, и никто не сказал.


Console.ReadLine() будет работать под .net 3.5
Если выше, то нужен фикс по ссылке
https://github.com/MailRuChamps/miniaicups/tree/master/agario/examples/csharp
