### ISSUE TITLE
0 read timeout error

### ISSUE THREAD

**Issue by adler3d** [MailRuChamps/miniaicups#230]
игры:
https://aicups.ru/session/207223/ 
https://aicups.ru/session/215091/

в первой игре стратегия "Олег Ш" упала на 0 кадре, хотя до этого его стратегия успешно выйграла где-то 30 игр.

во второй игре моя стратегия упала с "0 read timeout error", до этого с ней всё было почти нормально.

я уже видел "0 read timeout error" в своей старой стратегии один раз несколько дней назад, но тогда я потерял id`шник игры раньше чем сделал #224.

сейчас запустил свою стратегию используя #224 и скаченый лог игры - никакой задержки на старте не заметил.

**upd:**
ещё одна игра: https://aicups.ru/session/225675/

**upd2:**
ещё одна игра: https://aicups.ru/session/228222/

**upd3(похоже  "add drain to send" не помог):**
ещё: https://aicups.ru/session/299851/
ещё: https://aicups.ru/session/298195/

**Comment by adler3d** [comment]
Например баг может быть тут:
REQUEST_MAX_TIME = toint(os.getenv('REQUEST_MAX_TIME'), 5)

кто-то забыл или не успел установить в env REQUEST_MAX_TIME или там неправильно значение.

**Comment by dbf256** [comment]
Сегодня столкнулся с той же проблемой, игра https://aicups.ru/session_debug/241422/
В консоли "0 read timeout error", у меня никаких вычислений на первых тиках нет, прогнал такую комбинацию машинки/карты в локалраннере, все нормально.

**Comment by gitalph** [comment]
не 0 тик, но стратежка на нескольких ифах и времени жрать просто не может:
6973 - https://aicups.ru/session_debug/335376/
2888 - https://aicups.ru/session_debug/330632/

**Comment by adler3d** [comment]
https://aicups.ru/session/332675/

**Comment by adler3d** [comment]
https://aicups.ru/session/334259/

**Comment by adler3d** [comment]
Посмотрел десять страниц игр у Commandos`а где счёт 5 0 и ни нашёл ни с чём-то похожим на "0 read timeout error". Тоесть веротяность того что проблемма в стратегии, а не в системе больше 70%.

**Comment by adler3d** [comment]
https://aicups.ru/session/337345/

:(

**Comment by adler3d** [comment]
мм... может дело в том, что выделать 1 мегабайт на стеке плохая идея?

**Comment by adler3d** [comment]
> 
> 
> https://aicups.ru/session/337345/
> 
> :(

похоже удалось воспроизвести.
у меня сервак пишет что на первый кадр потребовалось 4394 ms. Если учитывать что мой сервак в 1.5 раза быстрее, то получается всё верно - система не виновата.

**Comment by adler3d** [comment]
> похоже у меня fgets читает 5КБ строку больше четырёх секунд

если делать вот так:
```
node ../visio_to_stdin.js 1 337345 nope|./main
```
то fgets зависает на несколько секунд.
если делать вот так:
```
node ../visio_to_stdin.js 1 337345 nope>log.txt
cat log.txt|./main
```
то ему хватает 0.208 ms.

Похоже все дело в передающей стороне, а не в стратегии.
Но почему тогда у Commandos`а нет ни одной упавшей игры?

**Comment by adler3d** [comment]
https://github.com/MailRuChamps/miniaicups/blob/b8e5969c1482f7656e53c897b698553064ad0d75/madcars/Runners/mechanic/strategy.py#L150
Так не честно.
Тут не должно быть timeout`а вообще, а так же замеров времени.
Я так понял, serverrunner.py и стратегия запускаются на разных машинах и между ними TCP link.
Этой строчкой вы как бы говорите - "все транспортные и стетевые расходы идут за счёт стратеии".
Хотя на той машине на которой выполняется стратегий есть ещё один посредник - та штука которая здоровается(hello_json) с serverrunner.py и читает/пишет в сокет. Все её задержки и баги идут в зачет стратегии.

По хорошему нужно чтобы все замеры времени делал та же прога которая пишет её в stdin, а не serverrunner.py запущщеный например на другом континете.

**Comment by adler3d** [comment]
ещё две:
https://aicups.ru/session/339858/
https://aicups.ru/session/339652/

посмотрел ещё 7 страниц игр у mortido - ни одного падения.
посмотрел его пример:
https://github.com/MailRuChamps/miniaicups/blob/b8e5969c1482f7656e53c897b698553064ad0d75/madcars/examples/C%2B%2B11/main.cpp#L13
он не проверят конец файла в отличии от меня.

попробую тоже убрать проверку.

**Comment by DragoonXen** [comment]
> > похоже у меня fgets читает 5КБ строку больше четырёх секунд
> 
> если делать вот так:
> 
> ```
> node ../visio_to_stdin.js 1 337345 nope|./main
> ```
> то fgets зависает на несколько секунд.
> если делать вот так:
> 
> ```
> node ../visio_to_stdin.js 1 337345 nope>log.txt
> cat log.txt|./main
> ```
> то ему хватает 0.208 ms.
> 
> Похоже все дело в передающей стороне, а не в стратегии.
> 
> Только не понятно почему тогда у Commandos`а нет ни одной упавшей игры?

щас нет. раз в 100 игр примерно

**Comment by DragoonXen** [comment]
в основном на 0 тике
За последние 1.5 дня:
343089 tick 3826
339201 tick 0
336210  tick 0
336163 tick 0
336449 tick 1515

**Comment by DragoonXen** [comment]
> ещё две:
> https://aicups.ru/session/339858/
> https://aicups.ru/session/339652/
> 
> посмотрел ещё 7 страниц игр у mortido - ни одного падения.
> посмотрел его пример:
> [miniaicups/madcars/examples/C++11/main.cpp](https://github.com/MailRuChamps/miniaicups/blob/b8e5969c1482f7656e53c897b698553064ad0d75/madcars/examples/C%2B%2B11/main.cpp#L13)
> 
> Line 13 in [b8e5969](/MailRuChamps/miniaicups/commit/b8e5969c1482f7656e53c897b698553064ad0d75)
> 
>  while (true) { 
> 
> он не проверяет конец файла в отличии от меня.
> попробую тоже убрать проверку.
> 
> upd:
> земенил "eof+fwrite+fflush" на "for(;;)+std::cout+std::endl" вроде помогло.

точно помогло или показалось?

**Comment by adler3d** [comment]
ну сейчас три страницы игр и ни одного падения на нулевом кадре.
вчера было что-то около пяти падений на трёх страницах.

**Comment by adler3d** [comment]
> 
> 
> > ещё две:
> > https://aicups.ru/session/339858/
> > https://aicups.ru/session/339652/
> > посмотрел ещё 7 страниц игр у mortido - ни одного падения.
> > посмотрел его пример:
> > [miniaicups/madcars/examples/C++11/main.cpp](https://github.com/MailRuChamps/miniaicups/blob/b8e5969c1482f7656e53c897b698553064ad0d75/madcars/examples/C%2B%2B11/main.cpp#L13)
> > Line 13 in [b8e5969](/MailRuChamps/miniaicups/commit/b8e5969c1482f7656e53c897b698553064ad0d75)
> > while (true) {
> > он не проверяет конец файла в отличии от меня.
> > попробую тоже убрать проверку.
> > upd:
> > земенил "eof+fwrite+fflush" на "for(;;)+std::cout+std::endl" вроде помогло.
> 
> точно помогло или показалось?
> 
> У меня то вывод изначально такой

сейчас спецально выкачал все логи игр с последних трех страниц - ни одного падения у меня.

**Comment by adler3d** [comment]
> 
> 
> в основном на 0 тике
> За последние ~1.5 дня:
> 343089 tick 3826
> 339201 tick 0
> 336210 tick 0
> 336163 tick 0
> 336449 tick 1515

ха, я только 5 0 игры смотрел, не думал что топ2 не смогу стоячего одолеть :)

**Comment by DragoonXen** [comment]
У меня последнее падение на 4 странице. Но страта не менялась

**Comment by adler3d** [comment]
> 336449 tick 1515

ну подение не на 0 кадре может быть из-за бага в стратегии.
сколько хоть cpu успела сожрать стратегия до подения?

**Comment by DragoonXen** [comment]
> > 336449 tick 1515
> 
> ну подение не на 0 кадре может быть из-за бага в стратегии.
> сколько хоть cpu успела сожрать стратегия до подения?

сейчас гляну, но не думаю, что больше полуминуты

**Comment by DragoonXen** [comment]
Кратко - да, съело очень и очень мало

**Comment by adler3d** [comment]
> 
> 
> Кратко - да, съело очень и очень мало

не если предположить что в стратегии бага нет, то тогда всё печально с сетью/proxy и протоколом обмена между serverrunner и proxy.

**Comment by DragoonXen** [comment]
> > Кратко - да, съело очень и очень мало
> 
> не если предположить что в стратегии бага нет, то тогда всё печально с сетью/proxy и протоколом обмена между serverrunner и proxy.

ну я вообще до вчера тоже видел только падения на нулевом. из где-то полутора десятка вот только две игры не на нулевом, но на моменте смены матча

**Comment by DragoonXen** [comment]
Ну и конечно же локально оно гонялось долго и счастливо, ни разу тормозов замечено не было..

**Comment by DragoonXen** [comment]
> ну сейчас три страницы игр и ни одного падения на нулевом кадре.
> вчера было что-то около пяти падений на трёх страницах.

кстати максимум было 3 падения на странице. и у этой же страты за 5 страниц ещё только 1 падение. так что очень сильный рандом

**Comment by adler3d** [comment]
> но на моменте смены матча

самое вероятное место для бага :)

я кстати тоже замечал, что у меня стратегия любит отрубатся при смене матча, надо будет тоже посмотреть повнимательнее на сообщение об ошибке.

**Comment by adler3d** [comment]
> кстати максимум было 3 падения на странице. и у этой же страты за 5 страниц ещё только 1 падение. так что очень сильный рандом

спасибо за статистику.

**Comment by DragoonXen** [comment]
> > но на моменте смены матча
> 
> самое вероятное место для бага :)


Это понятно, но тут всё же почти полная копипаста

ну и +
valdemar
mortido
у них также есть падения. И если последний в целом плюсы первый раз в руки взял, то в некосячность валдемара я более-менее верю

**Comment by DragoonXen** [comment]
ситуацию усугубляет то, что даже упавшую страту можно победить не со счётом 5-0, а тулзы для мониторинга стратегий мало кто имеет

**Comment by DragoonXen** [comment]
https://aicups.ru/session/350130/ - свежак. а я уж стал думать, что починили

**Comment by adler3d** [comment]
> свежак. а я уж стал думать, что починили

чтобы подчинить, нужно вот здесь:
https://github.com/MailRuChamps/miniaicups/blob/b8e5969c1482f7656e53c897b698553064ad0d75/madcars/Runners/mechanic/strategy.py#L149
заменить вот это:
```python
            before = datetime.datetime.now()
            z = yield from asyncio.wait_for(self.reader.readline(), timeout=REQUEST_MAX_TIME)
            if not z:
                raise ConnectionError('Connection closed')
            self.execution_time += (datetime.datetime.now() - before)
```
на что-то типа:
```python
            proxy_resp=yield from asyncio.wait_for(self.reader.send_to_proxy("""
              writeline(msg_bytes);
              before=datetime.datetime.now();
              line=readline();
              return {readline_time:datetime.datetime.now()-before,z:z};
            """,msg_bytes),timeout=PROXY_REQUEST_MAX_TIME)
            if not proxy_resp:
                raise ConnectionError('PROXY - SNAFU')
            proxy_resp=json.loads(proxy_resp.decode())
            self.execution_time+=proxy_resp.readline_time;
```

**Comment by adler3d** [comment]
всё же упал на 0 кадре:
https://aicups.ru/session/352168/

**Comment by DragoonXen** [comment]
Аналогично. Надеюсь реран всё же будет доступен

**Comment by dbf256** [comment]
Свежее: https://aicups.ru/session/365255/

**Comment by adler3d** [comment]
распарсил все логи своих игр из финала.

упавшие с "read timeout error" на 0 кадре:
```json
{"gameid":402091,"tick":0}
{"gameid":402343,"tick":0}
{"gameid":406501,"tick":0}
{"gameid":408720,"tick":0}
{"gameid":410816,"tick":0}
{"gameid":411590,"tick":0}
{"gameid":413886,"tick":0}
{"gameid":415643,"tick":0}
{"gameid":418660,"tick":0}
{"gameid":420580,"tick":0}
{"gameid":421343,"tick":0}
{"gameid":422393,"tick":0}
{"gameid":422460,"tick":0}
{"gameid":422706,"tick":0}
{"gameid":425443,"tick":0}
{"gameid":426810,"tick":0}
{"gameid":426843,"tick":0}
{"gameid":427966,"tick":0}
{"gameid":434712,"tick":0}
{"gameid":437450,"tick":0}
{"gameid":440710,"tick":0}
{"gameid":446443,"tick":0}
{"gameid":447068,"tick":0}
{"gameid":448186,"tick":0}
{"gameid":456705,"tick":0}
{"gameid":459166,"tick":0}
{"gameid":460341,"tick":0}
{"gameid":462805,"tick":0}
{"gameid":467775,"tick":0}
{"gameid":468615,"tick":0}
{"gameid":469868,"tick":0}
{"gameid":471443,"tick":0}
{"gameid":476468,"tick":0}
{"gameid":480033,"tick":0}
{"gameid":484880,"tick":0}
```

упавшие с "read timeout error" на не 0 кадре:
```json
{"gameid":396981,"tick":2754}
{"gameid":399091,"tick":3154}
{"gameid":404145,"tick":2244}
{"gameid":412720,"tick":211}
{"gameid":414715,"tick":4787}
{"gameid":424668,"tick":4379}
{"gameid":439856,"tick":439}
{"gameid":440832,"tick":4398}
{"gameid":455951,"tick":5561}
{"gameid":460380,"tick":5860}
{"gameid":471520,"tick":3252}
{"gameid":478668,"tick":6917}
{"gameid":492275,"tick":3985}
```

Сделайте rerun пожалуйста.

**Comment by dbf256** [comment]
Для перезапуска организаторы просили отправлять список игр на cups@corp.mail.ru
