### ISSUE TITLE
Не работает сервер как надо...

### ISSUE THREAD

**Issue by Bimlibob** [MailRuChamps/miniaicups#234]
Одна и та тже стратегия то работает, то не работает вообще. Большая разница между тем, что происходит в localRunner и на сервере. Почему так?

**Comment by kswaldemar** [comment]
Скорее всего ошибки в стратегии. Внимательно проверьте названия отправляемых команд (left, right, stop). Любая опечатка приведет к тому, что стратегия будет вести себя случайным образом (так придумали организаторы)

**Comment by Bimlibob** [comment]
В localRunner всё играет как надо. На сервере иногда играет, иногда просто стоит.

**Comment by kswaldemar** [comment]
Проверь, что нет никакого вывода в stderr, на сервере туда нельзя ничего печатать.

**Comment by Bimlibob** [comment]
Нет. Перед отправкой всегда отключаю System.IO. В файл ничего не пишу.

**Comment by Bimlibob** [comment]
Самое интересное то, что моя неработающая стратегия на 82 месте...Видимо не у одного меня такие проблемы.

**Comment by Bimlibob** [comment]
В Runnere всё нормально играет. Без сбоев. Как запрограммировал, так и ездит.

**Comment by AndreyVel** [comment]
Проверьте к-во передаваемых \n и вызывайте flush после каждой отправленной команды.
