### ISSUE TITLE
Не работает пересоздание игры через SEED

### ISSUE THREAD

**Issue by dbf256** [MailRuChamps/miniaicups#239]
Берем игру 
https://aicups.ru/session/275284/ - первая карта IslandHoleMap
Создаем новую игру, вставляя SEED 538460243868820754 в поле
Получается новая игра с почти таким же SEED, но на конце цифры отличаются
https://aicups.ru/session/275328/ - SEED : 538460243868820740
Получаем другую игру, первая карта PillCarcassMap

**Comment by DragoonXen** [comment]
Подтверждаю. Повторить игру не выходит. Если желается такая же карта - ждите следующего удачного случая.

Попутно очень хотелось бы возможность задания сочетаний карт и машинок, которые в игре хочется увидеть
