### ISSUE TITLE
Предложение новых правил захвата территории

### ISSUE THREAD

**Issue by ud1** [MailRuChamps/miniaicups#253]
Хочу предложить новые правила:

1. Для каждого игрока, который вошёл на свою территорию, строится множество клеток-кандидатов в добавление в его территорию. В это множество добавляются клетки:
  a) клетки шлейфа (т.е. все клетки, которые посетил игрок с момента выхода из своей территории и не входящие в его территорию, кроме клеток удалённых в пункте 3b в предыдущих тиках. Последняя точка, в которой находится сейчас игрок не принадлежит шлейфу).
  b) для всей карты рассматривается объединённое множество клеток территории игрока и его шлейфа, для него находятся все замкнутые контуры (каким-нибудь алгоритмом заливки) и все точки внутри этих контуров не принадлежащие территории игрока добавляются в список кандидатов.
2. Для каждого игрока проверятся, что клетка в которой он находится (т.е. клетка в которую он пришел, или если он ещё находится в движении между двумя клетками, то берётся клетка из которой он движется) является клеткой-кандидатом для другого игрока, если это так, то первый игрок умирает (т.е. его проглотил другой игрок). Когда игрок умирает, его клетки кандидаты больше не участвуют в дальнейших расчётах.
3. Для каждого игрока проверяется, что какая-либо из точек его шлейфа является клеткой-кандидатом другого игрока, если это так, то:
  a) если текущий игрок находится в клетке принадлежащей территории второго игрока, то первый игрок умирает, и дальше его клетки не участвуют в дальнейший расчётах.
  b) если текущий игрок находится в клетке не принадлежащей территории второго игрока, то текущий игрок теряет часть своего шлейфа, а именно все точки шлейфа которые являются клетками кандидатами другого игрока, а так же все точки шлейфа, который посетил игрок до этих клеток удаляются из шлейфа первого игрока.
4. Для всех клеток-кандидатов всех игроков проверяются, что если клетка является кандидатом только для одного из игроков, то она присоединяется к территории этого игрока. Если же на неё претендует больше одного игрока, то она становится нейтральной.

Под выражением "его клетки кандидаты больше не участвуют в дальнейших расчётах" имеются в виду в дальнейший пунктах, внутри же одного пункта итоги проводятся для всех игроков.

PS Пункт 3 наверно можно упростить, сделав его или более жестоким, или более мягким.

Более мягкий вариант (игрок не умирает):
3. Для каждого игрока проверяется, что какая-либо из точек его шлейфа является клеткой-кандидатом другого игрока, если это так, то игрок теряет часть своего шлейфа, а именно все точки шлейфа которые являются клетками кандидатами другого игрока, а так же все точки шлейфа, который посетил игрок до этих клеток удаляются из шлейфа первого игрока.

Более жестокий вариант (игрок умирает):
3. Для каждого игрока проверяется, что какая-либо из точек его шлейфа является клеткой-кандидатом другого игрока, если это так, то игрок погибает.

Целью данных правил - обеспечить, что:
1. не будет возможна ситуация, что клетки территории игрока будут формировать замкнутый контур, и внутри этого контура будут клетки не принадлежащие этому игроку.
2. будет честно разыграна ситуация, когда два игрока одновременно пытаются захватить общую территорию, и исход зависит от порядка обсчета игроков. Для этого в пункте 4 предлагается такие спорные клетки делать нейтральными.
Но выполняя это надо помнить случай, когда один игрок полностью окружает другого игрока, при этом игрок внутри в этот момент тоже может сделать захват внутренних клеток, внутренний игрок при этом должен помереть и все область достаться внешнему, нельзя допустить, чтоб при этом внутренние клетки мы засчитали нейтральными и у внешнего игрока образовалась дырка внутри его территории. Для этого служат пункты 2 и 3.

**Comment by ud1** [comment]
Полезная ссылка для пункта 1b
https://stackoverflow.com/questions/42968171/how-to-determine-if-a-grid-cell-is-within-an-enclosed-perimeter-of-cells

**Comment by Pro100AlexHell** [comment]
Я бы даже сказал что сейчас не очевидно, каким алгоритмом, в деталях, происходит захват территории. Даже наблюдая за тем что другие игры делали - не понятно временами что происходит. То что ud1 предложил ссылку с конкретной реализацией - плюс.

**Comment by alex3d** [comment]
В дополнение к написанному в тикете нужно определиться с 4-/8-свзязностью мира при поиске замкнутых контуров и использовать её везде (какую выбрать не особо важно).
Сейчас в раннере используется и то и другое: 
https://github.com/MailRuChamps/miniaicups/blob/1d056023930307219b906497c2dfd9bc37d6f1c4/paperio/local_runner/game_objects/territory.py#L48-L49
https://github.com/MailRuChamps/miniaicups/blob/1d056023930307219b906497c2dfd9bc37d6f1c4/paperio/local_runner/game_objects/territory.py#L122-L123
https://github.com/MailRuChamps/miniaicups/blob/1d056023930307219b906497c2dfd9bc37d6f1c4/paperio/local_runner/helpers.py#L46-L50

**Comment by alex3d** [comment]
> Более жестокий вариант (игрок умирает):
> 3. Для каждого игрока проверяется, что какая-либо из точек его шлейфа является клеткой-кандидатом другого игрока, если это так, то игрок погибает.

Я за этот вариант. При пересечении шлейфа игрок умирает, так что при захвате было бы логично сделать так же.

**Comment by Uzere** [comment]
Сейчас в чате нашли O(n^5) в текущем алгоритме заливки. Считаю, что нужно что-то менять в них

**Comment by Pro100AlexHell** [comment]
O(n^5) это что тут за "n" считается?
- кол-во точек которые прошел игрок? (длина шлейфа)
- площадь которая будет захвачена?
- еще чтото?

и не будет ли так что этот "n" по факту меньше, чем для случая O(N^2) где N намного больше?

**Comment by Pro100AlexHell** [comment]
Предлагаю скомбинировать алгоритм по ссылке
https://stackoverflow.com/questions/42968171/how-to-determine-if-a-grid-cell-is-within-an-enclosed-perimeter-of-cells
но перебирать не для каждой точки, потому что сложность (O) будет высокая

а оптимизировать его так:
визуально:
начало: http://prntscr.com/okh2rw
финал: http://prntscr.com/okh2we

т.е.
[0] делаем BBOX, обозначаем все точки "NOT CHECKED"
[1] выбираем случайно любую точку, проверяем алгоритмом по ссылке (выбранный ответ - 1й пост, не нулевой)
https://stackoverflow.com/questions/42968171/how-to-determine-if-a-grid-cell-is-within-an-enclosed-perimeter-of-cells
по результату она может быть
- снаружи (случайно): значит делаем так еще раз, в надежде получить внутри - [1] шаг
- внутри (случайно): значит [2] шаг
[2] крутим цикл во все 4 направления, и дополнительно закрашиваем смежные точки, чтобы для каждой из них не проверять [1 алгоритмом], т.к. мы уже итак знаем что они тоже внутри, а критерием завершения линии будет столкновение со стенкой (границей, в том числе только что нарисованной игроком, но она уже Set<Point> есть)

.. так делаем пока не покроем все точки

рандомизатор тут помогает выбрать не специфичным алгоритмом точку, а случайную, в надежде нарваться на Внутреннюю, и от нее циклом крутить еще несколько

если рандомизатор будет выдавать неверныен точки (снаружи много)
то в худшем случае сводится к оригинальному алгоритму [1] (по ссылке)

**Comment by Pro100AlexHell** [comment]
> 
> 
> Сейчас в чате нашли O(n^5) в текущем алгоритме заливки. Считаю, что нужно что-то менять в них

кстати проверил - сейчас тоже этот код смотрел

вот пример входных данных
get_voids_between_lines_and_territory
lines.size = 50 (например прошелся по 50 клеткам)
self.get_boundary().size = 30 (например, я так понял это границы а не set всех клеток, поэтому может быть не огромным)

get_neighboring(lp1) всегда вертает size = 8 (связность 8)
for lp2 in lines[:i_lp1 + 1] - вложенный цикл, когда с таким ограничением (c i индекса то это треугольник а не квадрат)
пока что O = ((lines.size^2) / 2) * 8 = (50 * 50)/2 * 8 = 10k

самый длинный путь тут (хотя есть и другие т.е по факту сложность выше)
path = self.get_path(start_index, end_index, boundary)

for index, point in enumerate(boundary) - O(boundary.length) = 30

siblings = self.get_siblings(point, boundary)
            for sibling in siblings:
- это 8

итого
O = ((lines.size^2) / 2) * 8 * boundary.length * 8 = (50 * 50)/2 * 8 * 30 * 8 = 4kk

4 миллиона вызовов метода
graph.add_edge(index, boundary.index(sibling), weight=1)

понятно что это не за 1 раз будет добавлен edge, и поиск дальнейший nx.shortest_path будет всего на 30*8 = 240 точках
но все таки..

**Comment by SannikovDmitry** [comment]
Алгоритм заливки менять не будем
