### ISSUE TITLE
На сайте нельзя загрузить .zip для Java 9 и Swift

### ISSUE THREAD

**Issue by NetLagina** [MailRuChamps/miniaicups#256]
На сайте нельзя загрузить .zip для Java 9 и Swift, только .java/.swift.

**Comment by stremin** [comment]
C Rust у меня тоже не получилось.

**Comment by tongohiti** [comment]
Для Rust всё нормально работает. В корень zip-архива нужно положить директорию `src/`, а уже в неё - файл `main.rs`.

Также в корень можно положить `Cargo.toml` - но он, к сожалению, игнорируется (но и не мешает). Это печально, очень хочется иметь возможность подтягивать свои библиотеки, как большом РАИКе. Я бы, к примеру, притащил бы Itertools, и ещё может быть Arrayvec.

**Comment by NetLagina** [comment]
fixed
