### ISSUE TITLE
Добавить time_limit_left

### ISSUE THREAD

**Issue by alex3d** [MailRuChamps/miniaicups#265]
Было бы полезно добавить в каждый тик новое поле: time_limit_left - время оставшееся у стратегии от `MAX_EXECUTION_TIME` (120 секунд).

**Comment by tongohiti** [comment]
Просто `time_left` же. Но передавать нужно float, если секунды, или сразу миллисекунды.

**Comment by 0x0badc0de** [comment]
А где это смотреть? Скачал несколько visio с последних игр, по слову time ничего в них нет.
Только локал ранер это умеет?

**Comment by tongohiti** [comment]
Странно, но локал раннер этого тоже не присылает. Хотя в коде ЛР есть следы реализации этой фичи. Не доделано?

**Comment by alex3d** [comment]
> А где это смотреть?

Пока на серверах мейла еще старая версия.
Как выкатят в продакшн в стратегию будет приходить `{"type":..., "params":..., "time_left":...}`
