### ISSUE TITLE
Неактуальное состояние шлейфа

### ISSUE THREAD

**Issue by actium** [MailRuChamps/miniaicups#270]
'width': 30
'speed': 5

'tick_num': 1
'position': [165, 255]
'lines': []

'tick_num': 7
'position': [135, 255]
'lines': []

Как видно из присылаемых данных об игровом состоянии, позиция изменилась на размер клетки, но шлейф не обновился.

**Comment by Pro100AlexHell** [comment]
хорошо бы добавить:
- воспроизводится?
- какие территории были принадлежащие игроку, т.е может он был на своей?

**Comment by actium** [comment]
отсутствующая в описанной ситуации клетка была добавлена в lines в следующем сообщении, но не было следующей клетки
другими словами, есть запаздывание с обновлением шлейфа

**Comment by Pro100AlexHell** [comment]
Всетаки tick: 7 это начало игры, вы не могли на 7 тик быть на нейтральной территории, вы были точно на своей, поэтому шлейф не начался (lines[] пустой), он начнется создаваться при первом входе в нейтрал территорию (не раньше 2 хода)
