### ISSUE TITLE
Баг в алгоритме пилы

### ISSUE THREAD

**Issue by spaceorc** [MailRuChamps/miniaicups#274]
Странно работает алгоритм отпиливания.

Смотрите: пила срабатывает ТОЛЬКО если пересекает территорию соперника, но убараются ВСЕ точки, лежащие с противоположной стороны от игрока, территорию которого режем, даже не входящие в разрезаемый компонент связности. Это кажется нелогичным.
![IMAGE 2019-07-21 23:19:57](https://user-images.githubusercontent.com/8295744/61595234-11d1ea00-ac0e-11e9-9573-c558523bb119.jpg)
![IMAGE 2019-07-21 23:20:11](https://user-images.githubusercontent.com/8295744/61595239-1ac2bb80-ac0e-11e9-98a5-b94cc8c17d18.jpg)

**Comment by Pro100AlexHell** [comment]
https://github.com/MailRuChamps/miniaicups/issues/319

**Comment by SannikovDmitry** [comment]
Давайте оставим так, как есть. Деление территории - случай тоже не очень частый.
