### ISSUE TITLE
окно локалраннера слишком большое в высоту, на ноуте не полностью влезает в экран.

### ISSUE THREAD

**Issue by aaafgcfg** [MailRuChamps/miniaicups#275]
![localrunner](https://user-images.githubusercontent.com/40723997/61619541-c2280880-ac77-11e9-9133-55188ae230e0.png)

**Comment by artzhookov** [comment]
PR: https://github.com/MailRuChamps/miniaicups/pull/279 + https://github.com/Nirenamid/miniaicups/pull/1
