### ISSUE TITLE
Building Docker image unauthorized

### ISSUE THREAD

**Issue by krutilin** [MailRuChamps/miniaicups#288]
nodejs9
docker build .
Sending build context to Docker daemon  2.048kB
Step 1/6 : FROM stor.highloadcup.ru/aicups/paperio_base
Get https://stor.highloadcup.ru/v2/aicups/paperio_base/manifests/latest: unauthorized

**Comment by estekhin** [comment]
перед сборкой специфических докеров следует локально собрать базовый с указанием тега, например, находясь в корне miniaicups:
```
docker build -t stor.highloadcup.ru/aicups/paperio_base paperio/dockers/base/.
```
