### ISSUE TITLE
Так и задумано что при взятии бонуса (ускорение или замедление) получается навечно сдвиг тайминга (обработка раньше других)

### ISSUE THREAD

**Issue by Pro100AlexHell** [MailRuChamps/miniaicups#290]
Мысленный эксперимент
1й игрок: условно берет ускорение на 1м шаге (не важно) и действует 2 шага (не важно):
тайминги: 1 = 6(+5) = 11(+5) = 17 (+6) = 23 (+6).
Другой игрок без бонуса: 1 = (+6) 7 = (+6) 13 = (+6) 19 = (+6) 25
2 тика - сдвиг - на всю оставшуюся игру (даже после окончания бонуса). А когда бонусы будут взяты несколькими игроками - новая каша, т.е. кроме того что это надо учитывать в нашем коде AI, это на механику влияет - очередности ходов. Не понял пока что на сколько критично.

**Comment by ud1** [comment]
Очевидно, что так и задумано, дополнительная особенность, которую можно детально учитывать в стратегии, или забить и рассчитывать приближенно. Если бы такого не было, то не было бы смысла в микроячейках, достаточно было сделать доску размером 31*31, ну и бонусов тогда бы не было.
