### ISSUE TITLE
Неверное определение предыдущего положения

### ISSUE THREAD

**Issue by FDoKE** [MailRuChamps/miniaicups#293]
В последнем коммите который фиксит шлейф - lastDirection не правильно используется,

в правильном контексте - lastDirection должно быть противоположное направление от текущего direction, а сейчас оно является - предыдущим:
пример:
идем направо
идем вниз

текущее - 0,0
предыдущее положение должно быть 0,1 (на 1 клетку вверх, так как двигались вниз)
а по текущей логике это - 1,0 (так как предыдущее движение - направо)

**Comment by actium** [comment]
tick: 3
position: [165, 255]
direction: None
	command: left

tick: 9
position: [135, 255]
direction: left
	command: left

tick: 15
position: [135, 285]
direction: up

Видимо, это проявление описанной ошибки.

**Comment by Pro100AlexHell** [comment]
если что - вроде пофиксено в контексте "уничтожения закрашиванием", на скок я вижу и по тестам, и по коду - теперь верно проверяется предыдущая и текущая (когда игрок в новой позиции).

хотя что у вас за проявления - может другие

**Comment by SannikovDmitry** [comment]
> если что - вроде пофиксено в контексте "уничтожения закрашиванием", на скок я вижу и по тестам, и по коду - теперь верно проверяется предыдущая и текущая (когда игрок в новой позиции).
> 
> хотя что у вас за проявления - может другие

ага
