### ISSUE TITLE
Требуется уточнить ограничения (многопоток, память, тайминги)

### ISSUE THREAD

**Issue by Pro100AlexHell** [MailRuChamps/miniaicups#294]
В чате слышал, но не подтверждено что:
1) Разрешен многопоток, т.е
- я делаю один Main поток, который отвечает в консоль командами и ждет команд JSON
- еще 1+ потоков Work, которые вечно крутятся и чтото считают (может быть все ходы наперед)

\ и особенно что если этих потоков много, т.е 100, это считается за вредительство системе, или легально?

> Действия, которые будут представлять риск нанесения ущерба проверяющей системе, будут рассматриваться как нарушение данных правил и приведут к дисквалификации участника.

\ а что если ненароком ктото сделает многопоток который забивает (100% загрузка) все CPU, т.е. во время расчетов чужих ботов - он также считает и искажает их тайминги - им меньше CPU свободного времени, но "миллисекунды идут"

2) Можно асинхронно получать ввод из stdin и в этот момент посчитать итог и выдать в stdout, а все это время вычислять дерево решений на будущее. Это по идее нарушает тайминги (120 сек на матч на время расчетов, а не учитывается во времени). И если нельзя - как это будет проверяться, по исходникам в автоматическом режиме?

3) 256 МБ лимит памяти RAM?  (число якобы с прошлых конкурсов)
Или безлимит? (ну в рамках приличного, условно пару гигабайт?)

(и вообще не обсуждаемый вопрос, кроме 3х выше)
4) Характеристики железа устойчивые во время тестов, во время раундов, и в финале?

\ по устойчивости в 1ю очередь важно чтобы потестить и увидеть что "AI укладывается в тайминги (5 сек на ход), расчитывая с такой то глубиной и такими то приемами". Ктото говорил про "пол сек на ход это много" но зависит от того на чем считать (1 ГГц или 4 Ггц, 1 CPU или все 16 CPU в многопотоке)
[по формуле 120 сек \ (1500 \ 6) (250 ходов при 6 скорости) = 0.48 сек на ход]

\ а что если НЕ-многопоток, а всеравно забивает 100% CPU, а этих CPU мало? Условно 6 участников, значит у каждого по правильному должен быть 1 CPU выделенный (affinity, т.е чтобы никто не считался на его же CPU, иначе будет CPU делиться между участниками), и 6-ядерный (по меньшей мере) суммарно

**Comment by FDoKE** [comment]
Решению дается только 1 ядро, можешь сделать хоть 100 потоков, но выполнять их будет всего 1 ядро)

**Comment by Pro100AlexHell** [comment]
Про 1 CPU это хорошо если правда, я просто хочу подтверждения от организаторов... ну и по всем пунктам.

**Comment by SannikovDmitry** [comment]
1 CPU, да
