### ISSUE TITLE
тут можно добавить что там была за строка, которую он не смог распарсить

### ISSUE THREAD

**Issue by aka-npou** [MailRuChamps/miniaicups#302]
https://github.com/MailRuChamps/miniaicups/blob/1afc6921915b59a0c79b13d9fad839779cda02bf/paperio/local_runner/clients.py#L202

**Comment by Pro100AlexHell** [comment]
Врятли простым способом можно поделить JSON на строки и распарсить по частям, а потом слить. А если не делить на части и парсить как сейчас - то exception\error не будет  (мне кажется) содержить номер строки. А если может (я ошибаюсь) - напишите как.

**Comment by aka-npou** [comment]
если что, я пытался понять почему у меня падают игры на 6 игроков когда я шестой. пробовал обратно отдавать то что дает на вход ЛР, но падало в ЛР.
оказалось ошибка у меня была в коде.
так что можно не писать что не смог распарсить, а смотреть это в файле скачанной игры(там видно что приходит). хотя может пока не всем удобно брать описание тика(лог игры) и смотреть свою стратегию как ответила и как приняла.





>Суббота, 27 июля 2019, 23:49 +03:00 от Pro100AlexHell <notifications@github.com>:
>
>Врятли простым способом можно поделить JSON на строки и распарсить по частям, а потом слить. А если не делить на части и парсить как сейчас - то exception\error не будет  (мне кажется) содержить номер строки. А если может (я ошибаюсь) - напишите как.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
chuk chuk

**Comment by SannikovDmitry** [comment]
ок
