### ISSUE TITLE
Печатать номер тика в LocalRunner

### ISSUE THREAD

**Issue by 0x0badc0de** [MailRuChamps/miniaicups#303]
Чтоб проще в логах потом найти нужный момент.
А вообще, неплохо бы чтоб хотя бы на паузу можно было поставить. В идеале - вообще контролы как на вебовском просмотрщике.

**Comment by tongohiti** [comment]
+1 за паузу в LocalRunner (и сделать хоткей P)
+1 за отрисовку номера тика в LocalRunner

Ещё предложил бы в LocalRunner статистику рисовать не поверх игрового поля, а в стороне (увеличив ширину окна LR), т.к. полупрозрачная плашка искажает цвета территории и шлейфа под ней, и становится трудно различать территорию и шлейф для 6-го игрока.
