### ISSUE TITLE
Какие версии питоновских пакетов в докере python3?

### ISSUE THREAD

**Issue by 0x0badc0de** [MailRuChamps/miniaicups#304]
Пытаюсь сделать
```
from scipy.spatial.qhull import Delaunay
```
и бот теперь стоит на месте, как-будто упал. Собрал имедж питона3 из этого репа - всё норм.
Почему валится - непонятно.
В идеале было бы неплохо, чтоб по кнопке "Скачать дамп" возвращалось что-то вразумительное.

**Comment by SannikovDmitry** [comment]
Installing collected packages: numpy, scipy, cython, joblib, scikit-learn, six, python-dateutil, pytz, pandas
Successfully installed cython-0.29.13 joblib-0.13.2 numpy-1.17.0 pandas-0.25.0 python-dateutil-2.8.0 pytz-2019.1 scikit-learn-0.21.2 scipy-1.3.0 six-1.12.0

Добавили

**Comment by 0x0badc0de** [comment]
Так это последние версии поставились прямо сейчас. Могу предположить, что локально?
А на серваке какие крутятся? Будут ли они те же в течение всего конкурса?
Или вы каждый раз ребилд имеджей делаете и докер-кеш не используется (т.е. версии всегда последние)?

Ну и оффтоп - дамп-то можно как-то скачать? :)

**Comment by SannikovDmitry** [comment]
> Так это последние версии поставились прямо сейчас. Могу предположить, что локально?
> А на серваке какие крутятся? Будут ли они те же в течение всего конкурса?
> Или вы каждый раз ребилд имеджей делаете и докер-кеш не используется (т.е. версии всегда последние)?
> 
> Ну и оффтоп - дамп-то можно как-то скачать? :)

Крутятся же. Выше версии.

Дамп починим

**Comment by 0x0badc0de** [comment]
Спасибо.
