### ISSUE TITLE
Рассинхронизация при захвате бонусов

### ISSUE THREAD

**Issue by lightkeeper217** [MailRuChamps/miniaicups#305]
Как я понял, бонусы пытаются увеличить/уменьшить текущую скорость до очередной кратной ширине ячейки. А время действия бонусов кратно 10 тикам. 
Предположим, что игрок захватывает два разных бонуса. 
Замедление действует 20 тиков, ускорение 10.
Тогда получим следующую ситуацию:
из-за наличия двух противоположных бонусов скорость не меняется, остаётся равной 5. Значит через 6 (6 от начала) тиков игрок вновь окажется в центре ячейки и сможет сделать ход. 
Через 4 (10) тика игрок пройдёт 20 точек, действие ускорения закончится, и следующая скорость будет равна 3. Значит через 3 (13) тика будет пройдено 29 точек (игрок ещё не получит возможность хода), а через 4 (14) тика - 32 точки (игрок уже не получит возможность хода) - т.е. будет двигаться в направлении (возможно за границы поля) которое для него вредно. на 20-ом тике будет пройдено 50 точек. после скорость станет равной 5. и только на 22ом тике игрок снова сможет поменять направление. т.е. игрок потеряет один раз возможность смены направления. а если замедление действует дольше, то может и на 4 клетки потерять управление.
Аналогично, если бы ускорение действовало дольше.

**Comment by Daramant** [comment]
> А время действия бонусов кратно 10 тикам.
Нет, время действия бонуса кратно 10 переходам между ячейками.
Бонус начинает и заканчивает свое влияние на игрока, когда игрок находится в центре ячейки.

**Comment by SannikovDmitry** [comment]
Ответ выше
