### ISSUE TITLE
Cell not added to trace, when opponent finishes loop in the same turn

### ISSUE THREAD

**Issue by eulerscheZahl** [MailRuChamps/miniaicups#313]
See https://aicups.ru/session/504377/ tick 1177:
My player moves on a cell, but it doesn't get added to the track.
In the same turn another player completes a loop (including the cell, my player is moving on).

Is that a bug (cell should be part of my track) or a feature?

**Comment by SannikovDmitry** [comment]
Hi! 
It was collision. No bug, only feature for solve collision problem.
