### ISSUE TITLE
Баг пилы - убила не всех

### ISSUE THREAD

**Issue by 0x0badc0de** [MailRuChamps/miniaicups#319]
https://aicups.ru/session/518897/ тик 1351. Синий и оранжевый оказались с одной стороны от своих территорий относительно разреза. У оранжевого их две, у синего - одна. Оранжевый выжил, синий - нет. У оранжевого выжила одна территория. Не должны ли были умереть оба?

**Comment by 0x0badc0de** [comment]
А. У синего территория отрезалась по краю, поэтому исчезла вся, а у оранжевого левый кусок территории и не должен был пострадать. Так?

**Comment by Pro100AlexHell** [comment]
По идее там проверка: игрок по какую сторону от пилы, и по противоложную сторону - удаляется вся его территория.

Скрины оттуда
http://prntscr.com/onjkss
http://prntscr.com/onjl5a

Поэтому у Красного и Синего (бирюзовый по RGB) удаляется часть что Выше линии пиления, т.к. они оба Ниже линии.

Однако я вижу баг для Желтого - он снизу линии, его территория выше линии, однако он ведет шлейф и видимо изза этого не отпилило? Не очевидно. По-мне - должна была удалиться вся территория Желтого.

**Comment by Pro100AlexHell** [comment]
Вобщем код там такой
if any([point in self.points for point in line]):
значит пилит только потерритории, и если игрок снизу а территория сверху, но не пересекает линию (как у Желтого) то не пилит ничего.
Вот связанная тема
https://github.com/MailRuChamps/miniaicups/issues/274

**Comment by 0x0badc0de** [comment]
Ай, я жёлтого и имел в виду, а не оранжевого.

**Comment by mmamaev** [comment]
Вот тут пила совсем не работает:
https://aicups.ru/session/576591/  тик 703
https://aicups.ru/session/576592/ тик 795

**Comment by 0x0badc0de** [comment]
@mmamaev работает, только рисует не в ту сторону, в которую пилит. На 703 тике видно, что красному слева отпилило, а нарисовалось, будто вверх стрельнула. Видимо, что-то подобное https://github.com/MailRuChamps/miniaicups/pull/326 на сервере появилось, где direction новые, а не старые :D

Глянул последние игры, https://aicups.ru/session/577668/ тик 1236 - то же самое. https://aicups.ru/session/577661/ 810. 

Походу отрисовку сломали.
