### ISSUE TITLE
"Съедание" врага более сильное убийство, чем наезд на шлейф?

### ISSUE THREAD

**Issue by 0x0badc0de** [MailRuChamps/miniaicups#327]
https://aicups.ru/session/574994/ тик 678
Красный собирается одновременно вернуться на свою территорию и пересечь шлейф жёлтого.
Жёлтый же собирается захватить территорию, где находится красный (съесть его).
В данном случае умер красный, видимо, потому что сервер решил, что его съели раньше, чем тот наступил на шлейф. А судя по коду шлейф вообще испаряется в самом начале до проверки is_loss https://github.com/MailRuChamps/miniaicups/blob/master/paperio/local_runner/game_objects/game.py#L237
Может убивать обоих и чистить шлейф в конце `game_loop`?

**Comment by Pro100AlexHell** [comment]
Шлейф испаряется при захвате для того чтобы одновременный захват 1м и наезд на шлейф 1го - 2м игроком - трактовались как "все живы, 1й захватил и шлейф исчез"

**Comment by 0x0badc0de** [comment]
Исходная у красного да - не его, а конечная - его территория, по которой проходит шлейф жёлтого.

Просто странно выходит - если тебе одновременно наступают на хвост и ты забегаешь домой, то спасся. А если одновременно тебя съедают и ты забегаешь домой (тем более на границе отъеденнего) - то нет.

Ну в общем да, согласен, что скорей всего править не будут - закрываю. Если решатся - переоткроют :)
