### ISSUE TITLE
Для отладки требуется добавление в local_runer настройки времени ожидания отклика

### ISSUE THREAD

**Issue by OlegJakushkin** [MailRuChamps/miniaicups#35]
Пусть мы разрабатываем в VS2017, C#. Логично желание поставить точку остановки и спокойно почитать что происходит в ходе выполнения стратегии. Насильный таймаут в 5 секунд лишает нас такой возможности. Пример:
![missingtimeoutsettings](https://user-images.githubusercontent.com/2915361/38060206-736155ee-32f2-11e8-9c39-6fd9501aa8db.gif)

Просьба добавить в local_runer опцию выставления времени таймаута хотя бы в 5 минут - это сильно упростит жизнь=)

**Comment by Xeenych** [comment]
А как включить такую отладку? Сделал вызов Debugger.Launch(), а окно Choost Just-In-time debugger не вылезает.
