### ISSUE TITLE
Добавьте плиз доскер для FreePascal (внутри созданный dockerfile)

### ISSUE THREAD

**Issue by tumaso** [MailRuChamps/miniaicups#37]
Я, к сожалению, в создании pull requests не силен, поэтому прошу добавить докер для FreePascal:

FROM ubuntu:16.04
MAINTAINER Igor Kuznetsov <garry_smith@mail.ru>

RUN apt-get install fp-compiler

ENV COMPILED_FILE_PATH=/opt/client/main
ENV SOLUTION_CODE_PATH=/opt/client/solution
ENV SOLUTION_CODE_ENTRYPOINT=main.pp
ENV COMPILATION_COMMAND='fpc -Cs67107839 -Mobjfpc -XS $SOLUTION_CODE_PATH/$SOLUTION_CODE_ENTRYPOINT -o$COMPILED_FILE_PATH 2>&1 > /dev/null'
ENV RUN_COMMAND='$COMPILED_FILE_PATH'

**Comment by tumaso** [comment]
Видимо стратегии на FreePascal никому не интересны, кроме меня?

**Comment by prospero78** [comment]
Я бы тоже попробовал на FreePascal

**Comment by BorisKolganov** [comment]
@tumaso добавь, пожалуйста, тестовую стратегию, чтобы я мог проверять работает ли контейнер. И добавь библиотеку для работы с JSON, если это необходимо

**Comment by prospero78** [comment]
Сейчас мучаюсь на golang. После FreePascal -- что python, что golang кажутся ущербными.
