### ISSUE TITLE
Очки за съедание выброса.

### ISSUE THREAD

**Issue by Bobral** [MailRuChamps/miniaicups#42]
В правилах не озвучено получение очков за съедание выброса. Хотя судя по локалранеру очки за это начисляются.
Проясните этот момент.

**Comment by sat2707** [comment]
Там же 0 :)
Это остаток функционала, от которого мы отказались

**Comment by Bobral** [comment]
Непонятно.
Т.е. за съедание выброса очки начисляться не будут, а локалраннер пока кривой? Верно?

**Comment by tongohiti** [comment]
Тоже из исходников локал раннера понял, что is_food выставляется и для еды, и для выбросов. А дальше общий код:
`````
        if (food->is_food()) {
            score += SCORE_FOR_FOOD;
        }
`````

**Comment by tongohiti** [comment]
> Там же 0 :)
> Это остаток функционала, от которого мы отказались

Там ноль для _**создания**_ выброса. А тут речь идёт про его _**поедание**_.

**Comment by sat2707** [comment]
Прошу прощения, не верно понял формулировку. Да, за съедание чужого выброса положены те же очки, что и за съедание еды, поправил в RULES.md
