### ISSUE TITLE
Баг local_runner(?) Масса в Circle хранится как целочисленное значение

### ISSUE THREAD

**Issue by ryzhikovas** [MailRuChamps/miniaicups#43]
В классе Circle масса целочисленная, при этом getter возвращает её в double. Все операции над массой работают с ней, как с числом с плавающей точкой. Это ошибка или фича?)

```
class Circle {
public:
explicit Circle(..., double _mass)...
double getM() const {
  return mass;
}
protected:
  int mass;
}
```

**Comment by xammi** [comment]
Действительно, предполагалось использование double
