### ISSUE TITLE
localrunner: Не рабоает отладочный визуализатор для спрайтов

### ISSUE THREAD

**Issue by dyatlov** [MailRuChamps/miniaicups#44]
Пишу вот так:
```
{"X":44.271887242357316,"Y":44.271887242357316,"Debug":"No food","Sprite":{"Id":"1","S":"dir 0"}}
```
В localrunner не видно ничего.

**Comment by kswaldemar** [comment]
Отладочной отрисовки в локал раннере нет. Видимо в правилах имеется в виду отладка в визуализаторе на сайте.

**Comment by tongohiti** [comment]
А можно добавить? Вроде несложно же. Сейчас данные два параметра не очень полезны.
