### ISSUE TITLE
local_runner: Player::fuse_timer не инициализирован

### ISSUE THREAD

**Issue by ryzhikovas** [MailRuChamps/miniaicups#46]
В начале игры в конструкторе Player::Player(...) fuse_timer не инициализируется. Как минимум на первом тике в json'е приходит мусор, например, "TTF":3473457.
P.S. Если замечу еще какие-то мелкие проблемы в runner'e, как их лучше оформить, PR или issue?

**Comment by sat2707** [comment]
Принято. Лучше PR конечно :)
