### ISSUE TITLE
Репитер

### ISSUE THREAD

**Issue by DragoonXen** [MailRuChamps/miniaicups#54]
На текущий момент на сайте можно скачать visio_[ID].log

внутри он выглядит так

>  #O=Options, A=Add, +=Change K=Kill, C=Command, T=Tick, W=World, F=Food, P=Player, V=Virus, E=Ejection
> OD T16 G1835 B50
> OW W990 H990 S959462412
> OF R2.5 M3.16843
> OV R16.0735 M40
> OP R8 M40
> OE R4 M15
> OFog S10
> AF5 X182 Y203
> AF6 X808 Y203
> AF7 X808 Y787
> AF8 X182 Y787
> AF9 X455 Y423
> AF10 X535 Y423
> AF11 X535 Y567
> AF12 X455 Y567
> AF13 X155 Y322
> AF14 X835 Y322
> AF15 X835 Y668
> AF16 X155 Y668
> AF17 X5 Y254
> AF18 X985 Y254

В целом понятно, что это за объекты, и как их читать, но...

Было бы очень неплохо иметь тул, который мог бы из этого сделать конвертацию в ровно те же данные, которые умеет обрабатывать стратегия.

Отдельной очень полезной фичей могла бы быть одновременная обрезка невидимых объектов в соответствии с правилами, т.о. получили бы готовый репитер для локального дебага игр, прошедших на сайте.

**Comment by sat2707** [comment]
Выложили `json`-логи стратегий.
Следующий шаг -- `json`-логи игр

**Comment by BorisKolganov** [comment]
Добавили конвертер лога в json
