### ISSUE TITLE
Один съел другого ни за что ни про что

### ISSUE THREAD

**Issue by Ir00man** [MailRuChamps/miniaicups#55]
http://aicups.ru/session/85548/

767 тик.
Масса желтого - 49 
Масса красного - 45
Один кушает второго.
Беспредел!
Куда смотрит коэф. MASS_EAT_FACTOR ?

**Comment by deniskolsanov** [comment]
# O=Options, A=Add, +=Change K=Kill, C=Command, T=Tick, W=World, F=Food, P=Player, V=Virus, E=Ejection
OD T16 G7500 B50
OW W990 H990 S1068768384
OF R2.5 M3.57623

здесь M3.57623 - масса еды
отсюда массы игроков:
40 + 5 * 3.57 = 57.85
40 + 9 * 3.57 = 72.13
57.85 * 1.2 = 69.42 < 72.13

Issue можно закрыть.
