### ISSUE TITLE
local_runner в ubuntu 17.10 (не unity)

### ISSUE THREAD

**Issue by CthulhuDen** [MailRuChamps/miniaicups#56]
Последняя (на данный момент) убунта, которая уже без unity.

![screenshot from 2018-03-29 22-36-40](https://user-images.githubusercontent.com/3912367/38109744-d2f0d192-33a1-11e8-9999-59ecffb944d8.png)

Как видно, игровое поле чуть вмещено вверх относительно рамки (и частично скрывается под меню)

**Comment by alex3d** [comment]
и под 16.04 тоже

**Comment by CthulhuDen** [comment]
Закинул PR #57, тестировал только на свой Ubuntu 17.10
