### ISSUE TITLE
Багофичи

### ISSUE THREAD

**Issue by alex3d** [MailRuChamps/miniaicups#59]
Хотелось бы понять баги это или фичи:
1) Безынерционный warp-двигатель: при движении в точку на расстоянии <3 мы телепортируемся в неё мгновенно https://github.com/MailRuChamps/miniaicups/blob/449863d10145dddf4ab5a4b90197367e6003f251/agario/local_runner/entities/player.h#L416
2) Если фрагмент что-то съел то на этом тике он проигнорирует команды split и eject
3) Туман войны на самом деле не сдвинут https://github.com/MailRuChamps/miniaicups/blob/449863d10145dddf4ab5a4b90197367e6003f251/agario/local_runner/entities/player.h#L143
4) "При количестве фрагментов больше одного, радиус обзора каждого из фрагментов дополнительно умножается на коэффициент по формуле: radius = 1.25 * radius * sqrt(fragments.count())" не похоже на код:
https://github.com/MailRuChamps/miniaicups/blob/449863d10145dddf4ab5a4b90197367e6003f251/agario/local_runner/constants.h#L113-L114
5) Масса игрока int или double? https://github.com/MailRuChamps/miniaicups/blob/449863d10145dddf4ab5a4b90197367e6003f251/agario/local_runner/entities/circle.h#L29
6) В начале игры радиус игрока не соответствует его массе (2*sqrt) https://github.com/MailRuChamps/miniaicups/blob/449863d10145dddf4ab5a4b90197367e6003f251/agario/local_runner/constants.h#L110-L111

**Comment by DragoonXen** [comment]
> 3. Туман войны на самом деле не сдвинут

Ещё добавлю - видимость считается всегда до центра

https://github.com/MailRuChamps/miniaicups/blob/449863d10145dddf4ab5a4b90197367e6003f251/agario/local_runner/entities/player.h#L143-L149

https://github.com/MailRuChamps/miniaicups/blob/449863d10145dddf4ab5a4b90197367e6003f251/agario/local_runner/entities/circle.h#L85-L88

а должно 

>  Туман войны означает, что боты получат информацию только о тех игроках, еде и выбросах, которые хотя бы частично попали внутрь радиуса обзора, с одним исключением - вирусы видны всем отовсюду.

**Comment by sat2707** [comment]
Пункт 1 исправлен в https://github.com/MailRuChamps/miniaicups/pull/65

**Comment by sat2707** [comment]
Пункт 4 исправлен в https://github.com/MailRuChamps/miniaicups/commit/288dd776027295300b4fc551b4b82e0bd06748cd

**Comment by sat2707** [comment]
Пункт 3 исправлен в https://github.com/MailRuChamps/miniaicups/pull/73

**Comment by sat2707** [comment]
Пункт 2 взят в работу

**Comment by sat2707** [comment]
Оставшееся исправлено в https://github.com/MailRuChamps/miniaicups/commit/f1d6efe0a90334ab9aae03af579264239eee3571

**Comment by sat2707** [comment]
На бою.
