### ISSUE TITLE
Название скрипта в "История решений"

### ISSUE THREAD

**Issue by tregor** [MailRuChamps/miniaicups#63]
Было бы очень удобно, если бы в "История решений" показывался не только ID решения, но и имя файла скрипта. Иначе сложно разобраться с версионностью собственного скрипта.
Ну или просто пользовательский комментарий к каждому своему решению.

**Comment by Karloid** [comment]
Можно пользоваться vcs и проставлять теги на загруженные решения с id решения 
![image](https://user-images.githubusercontent.com/2398460/38131803-13ea425e-3411-11e8-84a6-372889228a21.png)
