### ISSUE TITLE
GOPATH для go-docker

### ISSUE THREAD

**Issue by 1stborn** [MailRuChamps/miniaicups#64]
Не передается ( передается по умолчанию ) переменная окружения, что не позволяет использовать ничего кроме main.go

solution/main.go:7:2: cannot find package "***" in any of:
	/usr/lib/go-1.10/src/*** (from $GOROOT)
	/root/go/src/*** (from $GOPATH)

Добавьте GOPATH который смотрит в solution

`
ENV COMPILATION_COMMAND='GOPATH=$SOLUTION_CODE_PATH go build -linkshared $SOLUTION_CODE_PATH/main.go  2>&1 > /dev/null'
`

**Comment by tongohiti** [comment]
Workaround: используйте пока локальные импорты, они работают. Сам так делаю.
`````main.go
import "./mypackage"
import "../another"
`````

**Comment by BorisKolganov** [comment]
Решается локальными импортами.
