### ISSUE TITLE
C# .NET: Добавление библиотеки accord-net framework

### ISSUE THREAD

**Issue by OlegJakushkin** [MailRuChamps/miniaicups#75]
Добавьте пожалуйста для **C#** [**accord-net framework** ]( https://github.com/accord-net/framework ).

**Аргументы за:**
 - там [есть KDTree](http://accord-framework.net/docs/html/T_Accord_Collections_KDTree_1.htm) c ApproximateNearest, GetNodesInsideRegion
 - Методы [RANSAC line](http://accord-framework.net/docs/html/T_Accord_MachineLearning_Geometry_RansacLine.htm) например,  
 - Neural Network Library. 
 - Она [LGPL](https://github.com/accord-net/framework/blob/development/LICENSE).

[Гайды](https://github.com/accord-net/framework/wiki/Linux) [по установке в Linux](https://github.com/accord-net/framework/tree/v3.8.0#with-mono-in-linux)

**Аргументы против:**
- Не во всех языках есть аналоги -  ANN для KNN, Regression,  Neural Network Library. Это спровоцирует неравенство возможностей. Это как дать разработчикам на Питоне использовать _TF_ вместе с _scipy_.
 - В ней [горы библиотек](https://github.com/accord-net/framework/releases ) которых могут быть использованы максимум 3-4 в нашей ситуации. При этом в разных решениях разные.

**Предложение:**
Добавить набор пакетов касающихся [Scientific Computing](http://accord-framework.net/intro.html) и из зависимости (общим весом менее 6mb):

1. Accord
2. Accord.Genetic
3. Accord.Math.Core
4. Accord.Math
5. Accord.Statistics 
6. Accord.MachineLearning
7. Accord.Neuro

**Установка через Nuget:**
```
Install-Package Accord.Neuro
Install-Package Accord.MachineLearning
Install-Package Accord.Statistics
Install-Package Accord.Math
```

**Comment by OlegJakushkin** [comment]
Теперь в C# версии могут стать доступны некоторые возможности которые есть у пользователей Питона (у которых из  библиотек `numpy scipy cython scikit-learn keras pandas tensorflow==1.5.0`)

**Comment by sat2707** [comment]
Будет рассмотрено до 5 апреля
