### ISSUE TITLE
В отладочном веб интерфейсе у жирных агентов не видно направление движения

### ISSUE THREAD

**Issue by OlegJakushkin** [MailRuChamps/miniaicups#78]
Пример:
![missingdebugarrows](https://user-images.githubusercontent.com/2915361/38150364-46b18d4a-3467-11e8-974e-7a4af01168db.gif)

[Исходник реплея](http://aicups.ru/session_debug/86250/)

В отладочном веб интерфейсе у жирных агентов частично не видно направление движения.

**Comment by BorisKolganov** [comment]
Теперь направление показывается до конкретной точки (куда указывает команада от стратегии)
