### ISSUE TITLE
Видимость жирных амеб

### ISSUE THREAD

**Issue by Xeenych** [MailRuChamps/miniaicups#80]
Похоже, что большая, толстая амеба не будет видна, пока ее центр не попадет в поле зрения.
Таким, образом, маленькая амеба никогда не сможет увидеть достаточно большую.

**Comment by alex3d** [comment]
уже исправили https://github.com/MailRuChamps/miniaicups/commit/887a9b2d04171abe140b234afb5dcb008a2c169f
