### ISSUE TITLE
При создании игр не работает поиск по нику

### ISSUE THREAD

**Issue by 99peso** [MailRuChamps/miniaicups#82]
![2018-03-31 10-04-00](https://user-images.githubusercontent.com/30184267/38160760-5efde114-34cb-11e8-9c2a-10a073fe1837.png)

**Comment by FDoKE** [comment]
Меня то за что :( а так да, странно что этого нет..

**Comment by 99peso** [comment]
так выбрал лучшего игрока же :)

**Comment by DragoonXen** [comment]
лучший лесоруб в нашем лесу ифов
