### ISSUE TITLE
SEED для инициализации ГПСЧ

### ISSUE THREAD

**Issue by kudlai** [MailRuChamps/miniaicups#91]
Хотелось бы, чтобы при передаче параметров в начале раунда стратегия получала в том числе и SEED - уникальное для каждой игры большое число.
Это позволит при воспроизведении лога ввода получаемого стратегией от runner'а получать всегда одно и то же поведение, при использовании ГПСЧ.

**Comment by BorisKolganov** [comment]
SEED есть в логе для визуализации игры
